### ISSUE TITLE
wait-until command continues to wait until the end timeout, eventhough the command is successfull independently

### ISSUE THREAD

**Issue by kgk-bytes** [nickjj/wait-until#6]
First of all, thank you very much for creating this handy tool. in recent days we came across one issuse, as mentioned below, however, we do not see this issue in the earlier versions of the same same wait-until tool. Can you please take a look once?
Thank you in advace.

What is seen is as follows,

when we execute the below command independently, the command comes out fine.
Working - the below command works independently and comes out as it is able to find the string.
docker-compose exec -T AdminCntr grep -iq 'The server sarted in RUNNING mode.' /u01/oracle/user_projects/domains/access_domain/logs/as.log

not working - although the command was successful in the above step it fails when we use wait-until
./wait-until "docker-compose exec -T AdminCntr grep -iq 'The server started in RUNNING mode.' /u01/oracle/user_projects/domains/access_domain/logs/as.log" 10
**command was never successful, aborting due to 10 s timeout!**

**Comment by nickjj** [comment]
Hi,

So for clarity you're saying with this command:

```
./wait-until "docker-compose exec -T AdminCntr grep -iq 'The server started in RUNNING mode.' /u01/oracle/user_projects/domains/access_domain/logs/as.log" 10
```

The v0.1.1 version of `wait-until` fails with a timeout but the older v0.1.0 version of `wait-until` works with the same command?

Are you 100% sure you're running the command in the same environment? What happens if you change 10 to 100? Does it eventually work?

Can you come up with a reproduceable test case?

**Comment by nickjj** [comment]
Thanks, I'm able to reproduce this here when using the postgres connection test from the documentation.

I just reverted #5 which changed the behavior of the script and pushed v0.1.2 which uses the old version of the script which is working.
