### ISSUE TITLE
Add as answer to https://stackoverflow.com/questions/51974418/wait-until-a-condition-is-met-in-bash-script

### ISSUE THREAD

**Issue by jcrben** [nickjj/wait-until#7]
I added a comment noting your solution over at https://stackoverflow.com/questions/51974418/wait-until-a-condition-is-met-in-bash-script but might be better as an answer. Improves discoverability.

**Comment by nickjj** [comment]
Thanks.

I don't have a StackOverflow account, I think keeping a link to the project works as long as they're ok with that.
